### ISSUE TITLE
State not updating on set()

### ISSUE THREAD

**Issue by maarten-22** [web-ridge/react-ridge-state#17]
I am not sure what is going on here but the set state seems to never fire any updates inside my components. 
```ts
// toastState.ts
export const toastState = newRidgeState<IToastNotification[]>([]);
```

```ts
// toast logic
export const showToastNotification = (toast: IToastNotification) => {
    const currentToasts = toastState.get();
    currentToasts.unshift(toast);
    toastState.set(currentToasts);
}
```

```ts
// app root component
export default function App() {

  const currentToasts = toastState.useValue();

  console.log(currentToasts);
   return (
      // main app content
    );
}
```

When I call `showToastNotification()`, the `console.log(currentToasts)` in my app root is never called. Only when manually hot reloading my app I get the new values logged to the console. I am using Expo.

**Comment by RichardLindhout** [comment]
The state should be immutable because it won't see updates to the array otherwise (because it's the same reference)

It's the same as how react props will work if you have a React.memo component or PureComponent. It's also how other state libraries like Redux etc work. The state needs to be immutable in order to see if an object has changed.

If you want to use unshift you should look up the inner part or make a new array and unshift it

https://stackoverflow.com/questions/37198832/javascript-array-unshift-in-an-immutable-way

**Comment by maarten-22** [comment]
Ah ofcourse. Should have done that. Don’t know how I missed that, it even says in the docs 😅.
`(prevState) => [...prevState, { id: 1, name: "NiceProduct" }]`
